### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ShadowKnight64** [LakiSM64JS/LakiSM64JS.github.io#3]
Is there any chance you can make all of the text and buttons on signs?

**Comment by LakiSM64JS** [comment]
What do you mean on signs?

**Comment by ShadowKnight64** [comment]
Like instead of the text just floating there, they could be posts on a bulletin board on the roof or something.

**Comment by ShadowKnight64** [comment]
They still can be buttons, but they look out of place just floating there.

**Comment by LakiSM64JS** [comment]
Actually i'm gonna change them to a bulletin board thinking about it now
