### ISSUE TITLE
no problems here i just wanted to recommend that you should put the favicon in the img folder

### ISSUE THREAD

**Issue by 404Dev-404** [LakiSM64JS/LakiSM64JS.github.io#4]
if it breaks it then sorry

**Comment by LakiSM64JS** [comment]
Ima try that but next time suggest things in the discord in the #site-suggestions channel please and don't report it as an issue

**Comment by 404Dev-404** [comment]
> Ima try that but next time suggest things in the discord in the #site-suggestions channel please and don't report it as an issue

yeah i forgot about that
